version: '3'


networks:
  fullcycle-net:
    driver: bridge

services:
  db: 
    image: biarms/mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle-net

  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - fullcycle-net
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    networks:
      - fullcycle-net
    depends_on:
      - app